// <auto-generated />
using Library.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260927210123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Authors_FullName");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Robert C.",
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Martin",
                            LastName = "Fowler"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Eric",
                            LastName = "Evans"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Gang",
                            LastName = "of Four"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Andrew S.",
                            LastName = "Tanenbaum"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            PublicationYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 2,
                            PublicationYear = 2017,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CategoryId = 1,
                            PublicationYear = 1999,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CategoryId = 2,
                            PublicationYear = 2002,
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CategoryId = 2,
                            PublicationYear = 2003,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            CategoryId = 2,
                            PublicationYear = 1994,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            CategoryId = 3,
                            PublicationYear = 2014,
                            Title = "Modern Operating Systems"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_Name");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Libros sobre desarrollo de software y programación",
                            Name = "Programación"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Patrones, principios y diseño de sistemas",
                            Name = "Arquitectura de Software"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fundamentos teóricos y algorítmicos",
                            Name = "Ciencias de la Computación"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Diseño, modelado y gestión de bases de datos",
                            Name = "Base de Datos"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
                {
                    b.HasOne("Library.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Library.Domain.Common.ValueObjects.Isbn", "Isbn", b1 =>
                        {
                            b1.Property<int>("BookId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Isbn");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");

                            b1.HasData(
                                new
                                {
                                    BookId = 1,
                                    Value = "978-0132350884"
                                },
                                new
                                {
                                    BookId = 2,
                                    Value = "978-0134494166"
                                },
                                new
                                {
                                    BookId = 3,
                                    Value = "978-0201485677"
                                },
                                new
                                {
                                    BookId = 4,
                                    Value = "978-0321127426"
                                },
                                new
                                {
                                    BookId = 5,
                                    Value = "978-0321125217"
                                },
                                new
                                {
                                    BookId = 6,
                                    Value = "978-0201633610"
                                },
                                new
                                {
                                    BookId = 7,
                                    Value = "978-0133591620"
                                });
                        });

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Isbn")
                        .IsRequired();
                });

            modelBuilder.Entity("Library.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Library.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
